name: deploy package
on:
  release:
    types: [ published ]
jobs:
  tox-ci:
    uses: QualiSystems/.github/.github/workflows/package-tox-py.yml@master
    with:
      pre-commit-py-version: "3.10"
      build-py-version: "3.10"
      tests-py-version: "3.10"
  pypi-deploy:
    needs: tox-ci
    uses: QualiSystems/.github/.github/workflows/package-deploy-pypi.yml@master
    secrets: inherit
